### ISSUE TITLE
Method  makeProjectFinal in Project not working

### ISSUE THREAD

**Issue by JustSomeGirlWithoutAMustache** [CSC207-UofT/course-project-csc207_stackoverflowers#10]
I got a 'cannot resolve method' error for  makeProjectFinal in Project.java, despite the method is well-defined. Could anyone help me out?

**Comment by Maryyeah** [comment]
I saw this issue on IntelliJ too, just pushed a change to fix it: turned out the skillsCompatibitiesHelper was missing an end bracket.
