### ISSUE TITLE
Interview level ending before hiring 6 interns

### ISSUE THREAD

**Issue by Jacobcansleepnow** [CSC207-UofT/course-project-csc207_stackoverflowers#103]
After hiring 2 interns, hiring the third intern gives you the prompt: "sorry you have already hired 6 interns......". Preventing the player to continue the hiring process.

**Comment by hermonen** [comment]
yeah rn it stops at 2 interns bc of testing, game maker only makes 3 interns so I put the limit at 2 to test, when we change game manager back to producing 6 interns it'll be changed back to 6 (that's why the prompt still says 6)

**Comment by hermonen** [comment]
you should be able to continue the hiring process by typing the name of the intern you want to fire or when you type 'end interview'

**Comment by Maryyeah** [comment]
ok then you can change it back to six now!! or else the monthLevel won't be able to finish ;)

**Comment by hermonen** [comment]
ahh okay lemme change it!

**Comment by hermonen** [comment]
just changed to 6!

**Comment by hermonen** [comment]
my game manager is still only producing 3 interns tho, hopefully, yours is producing 10? otherwise the condition will not work

**Comment by Maryyeah** [comment]
yep GameManager in main is producing 10 interns now. Also, you can use hashtags to point me to the pull request you did to solve this issue. #105  Andd since you did most of the fixing, you can close this issue if you want!

**Comment by hermonen** [comment]
fixed on pull request #105
