### ISSUE TITLE
Sphase not running

### ISSUE THREAD

**Issue by Jacobcansleepnow** [CSC207-UofT/course-project-csc207_stackoverflowers#109]
It will show "
null
Welcome to HRSimulator! To start the game, please enter your name.
To load an already existing game under your name, please type 'load <name>'.

Process finished with exit code 0
"
After investigation, the problem is located at Response Tree Maker, line 150.
There is a null pointer exception there. I'm assuming that it is caused by attempting to remove an item from an empty list.

**Comment by Maryyeah** [comment]
I've tried running SPhase in main and I seem to not encounter this issue?

**Comment by frzana1012** [comment]
I don't have this issue either. I think your main is not updating properly. Compare line 150 from the repo to line 250 on your intelliJ and see if its the same or not.
