### ISSUE TITLE
Intern's response not correct sometimes?

### ISSUE THREAD

**Issue by Maryyeah** [CSC207-UofT/course-project-csc207_stackoverflowers#111]
See screenshots: sometimes the response is empty, other times it includes the question?
![Screen Shot 2021-12-04 at 9 25 05 AM](https://user-images.githubusercontent.com/80537268/144713737-ae89afea-7c3c-4621-9ab6-93ad1f9a9dee.png)

![Screen Shot 2021-12-04 at 9 30 41 AM](https://user-images.githubusercontent.com/80537268/144713742-9dd8d92a-c1d1-4973-a347-26589206c22d.png)

**Comment by Maryyeah** [comment]
ok now that i've reran SPhase, the issue is now that the intern doesn't have any response anymore.

**Comment by Maryyeah** [comment]
Oh now I see the issue: when uppercase A is typed, the intern has a response, when lowercase a is typed, no response but not caught as an exception:
![Screen Shot 2021-12-04 at 10 02 40 AM](https://user-images.githubusercontent.com/80537268/144714340-791e8260-0070-40ad-b722-c22d46d9ed9b.png)

**Comment by frzana1012** [comment]
just fixed this issue. Will be making a pull request now. Thank you for bringing this to my attention!
