### ISSUE TITLE
GamePrompts formatting

### ISSUE THREAD

**Issue by Maryyeah** [CSC207-UofT/course-project-csc207_stackoverflowers#112]
I'm opening this issue because we could have some better formatting for our SPhase,, but not top priority, if anyone has time I guess you could look into how our formatting could be better?
1. when two projects meet, they don't have a proper new line in between, could be added?
![Screen Shot 2021-12-04 at 10 07 47 AM](https://user-images.githubusercontent.com/80537268/144714515-e1cc37ab-baee-40f1-bd31-6c609492ec18.png)

**Comment by Maryyeah** [comment]
![Screen Shot 2021-12-04 at 10 36 56 AM](https://user-images.githubusercontent.com/80537268/144715441-5ee97524-8b4d-40dc-aab9-b68e1b4d44d1.png)
Asking "who do you want to give this skill to?" is not clear enough for what commands the player can type

**Comment by frzana1012** [comment]
also I think jacob was in charge of this so he should know more about what commands we can use here. Please check.

**Comment by JustSomeGirlWithoutAMustache** [comment]
Fixed
