### ISSUE TITLE
One Project for each time interval, or two projects each time??

### ISSUE THREAD

**Issue by Maryyeah** [CSC207-UofT/course-project-csc207_stackoverflowers#22]
Right now the getProject() in HRSystem will return a single project for that month. However, aren't we designing so that there are multiple projects for each month?

**Comment by hermonen** [comment]
Yes, we would need to assign two projects for each month. In that case, do we modify the code calling getProject() to call it twice, or do we just modify getProject itself to return two projects?

**Comment by frzana1012** [comment]
I think it should return two projects? theoretically speaking since parameter is current month, for numbers 1-2, it should return the first two projects and for 3 and 4 it should return the second two projects. but what about the final project? does getproject() also handle the final project?

**Comment by Maryyeah** [comment]
modify getProjects to return an ArrayList of two projects. And also would need to be aware where this would be used, if you could change everything related that would also be great. The final project should also be handled this way, we don't want to make things more complicated.
