### ISSUE TITLE
MonthMaker Prompt Usage 

### ISSUE THREAD

**Issue by frzana1012** [CSC207-UofT/course-project-csc207_stackoverflowers#27]
While I was writing some of the prompts left in GamePrompts, I noticed the method startofMonthPrompt() in class MonthMaker uses start_of_month_prompt_before_name twice when its NOT final month and I was wondering if this was done on purpose or if it was just a mistake? 

Also for when it IS the final month, is the final_month_prompt_after_project just the same as start_of_month_prompt_after_project? If so, you can just use start_of_month_prompt_after_project, if it is NOT the same, please specify what the final_month_prompt_after_project needs to specify and I will make the appropriate changes. Thank you

**Comment by Maryyeah** [comment]
Hi, I fixed the start_of_month_prompt problem, and for final_month_prompt_after_project, yea it is kinda the same with start_of_month_prompt_after_project. I copied and pasted it for now, but I wanted to leave it as different prompts so that we have the option to change one or the other.
