### ISSUE TITLE
SPhase not Working 

### ISSUE THREAD

**Issue by frzana1012** [CSC207-UofT/course-project-csc207_stackoverflowers#67]
Can Enam run Sphase and debug it to see what the issue is and why the first prompt is not returning the list of InterviewInterns?

**Comment by Maryyeah** [comment]
SPhase is running now, it is successfully going into interviewLevel bu there is a lot to change. Looking through why the list of InterviewInterns are not returned right now.

**Comment by Maryyeah** [comment]
for now, SPhase is able to handle the three universal commands.

**Comment by Maryyeah** [comment]
Solved! Turns our GameGenerator was updating a different HRSystem than the one that is inside GameMaker. Fixed so that there is the one and only HRSystem updated.
