### ISSUE TITLE
Intern Skills Float too many digits

### ISSUE THREAD

**Issue by Maryyeah** [CSC207-UofT/course-project-csc207_stackoverflowers#80]
The interns skills are too long of a float. Should make it shorter to be easier to display to the player. Perhaps two digits long?

**Comment by frzana1012** [comment]
(Hopefully) Changed the method so it now should show only 2 decimal places, however since I am currently working on ResponseTreeMaker I cannot test/push at the moment. Will test once responseTreeMaker is fully finished.

**Comment by frzana1012** [comment]
the newest pull request now has solved this issue :)
